### ISSUE TITLE
when will the code be ready

### ISSUE THREAD

**Issue by jhzhang19** [NVlabs/viewpoint-robustness#1]
Hi, it's a good job. May i ask when will the code be ready?

**Comment by tzofi** [comment]
Hi @jhzhang19 , thanks for your interest in our work. We will have the code for interacting with the datasets released in the next few days/week. Thank you for your patience.

**Comment by tzofi** [comment]
@jhzhang19 , the code for preprocessing and dataloading has been committed. Closing this out. Please let us know / create a new issue if you have any questions when using the data - thanks!

**Comment by rockywind** [comment]
Hi, thank you for sharing the great work. When will release  the training code?

**Comment by tzofi** [comment]
@rockywind thank you for the interest in our work. Unfortunately we are not able to release the code used for novel view synthesis, but it is based off of [this implementation](https://github.com/facebookresearch/worldsheet). Our changes are described in the paper. For BEV segmentation, we use [Lift Splat Shoot](https://github.com/nv-tlabs/lift-splat-shoot) and [Cross View Transformers](https://github.com/bradyz/cross_view_transformers).

**Comment by rockywind** [comment]
@tzofi Thank you for help.
