### ISSUE TITLE
change camera, difference intrinsic parameter, can use the repo?

### ISSUE THREAD

**Issue by northeastsquare** [NVlabs/viewpoint-robustness#2]
Thank you for your great work, I learn a lot.
After read the paper, I have a question.
If I have one car with camera sony, data labeled.
Then I have another car with camera hp , different manufacturer, Can I use the sony camera's labeled data merged to train model, with the method you mentioned in paper?

**Comment by tzofi** [comment]
@northeastsquare , thank you for your interest in our work. If I understand your question correctly, you'd like to transform your images captured from a Sony camera to the parameters of an HP camera, and use the original labels to train a model. Our method can certainly help with this, depending on a few things:

1. What are the differences between the Sony and HP camera? Our method can transform data to different camera parameters (intrinsics) and extrinsics (we focus on extrinsic changes in our paper), but not other changes, in its current form.

2. What is your task? We focus on BEV segmentation in our work, meaning the labels are simply 3D points, which can easily be transformed to different camera coordinate systems. If your task includes semantic information (e.g. semantic segmentation), more sophisticated methods would be needed to transform the labels. However, if you're doing BEV segmentation or 3D object detection, transforming the labels should be straightforward.

I hope this helps. Please let me know if you have any more questions!
