### ISSUE TITLE
google.protobuf has no attribute pyex

### ISSUE THREAD

**Issue by veinlove55** [NVlabs/viewpoint-robustness#3]
Dears,
    I'm studying your project, and I try this command
`python drivesim.py --dataroot ./DRIVESim_datasets --session 5f8f235e-9304-11ed-8a70-6479f09080c1 --dataset_idx 0 --rectify 1`
But I got this error in this file 'data_tools.py' LOC 800
`AttributeError: module 'google.protobuf' has no attribute 'pyext'`
In this link [https://github.com/protocolbuffers/protobuf/issues/13300](url) it mentioned google.protobuf.pyext._message is an internal-only module, as indicated by the leading underscore. It is removed completely in 4.21.x.
So which version is used in this project?

**Comment by tzofi** [comment]
@veinlove55 Thanks for the question! We used protobuf 3.20.1 in our environment. I have updated the requirements.txt accordingly. Please let me know if you have any other issues and I'll be happy to help!
