### ISSUE TITLE
Simulated CARLA Dataset Rendering Code

### ISSUE THREAD

**Issue by abhi1kumar** [NVlabs/viewpoint-robustness#4]
Hi Tzofi,
Thank you for releasing your simulated CARLA image dataset. Since CARLA also provides depth and semantic labels along with images, we wanted to get the simulated CARLA images' depth and semantic segmentation labels. 

It would be great if you could release your CARLA rendering code so that we could generate depth and semantic segmentation labels of the released CARLA images on our end.

**Comment by tzofi** [comment]
Hi @abhi1kumar, The code we used for rendering the CARLA datasets is available in the following zip file:

[https://drive.google.com/file/d/1-1R1ggYuPdU9_LF3XV5Tp6SZ131T1emU/view?usp=sharing](https://urldefense.com/v3/__https://drive.google.com/file/d/1-1R1ggYuPdU9_LF3XV5Tp6SZ131T1emU/view?usp=sharing__;!!HXCxUKc!0jnAEs1SEsUbl9nOaJSQNpp1jD1QQBp1wR777e9RUmf8w4MSsguFQ2rR_Xfxc63N_jfIMXkiwtsY3w$)

Please check the README in the zip for instructions. If you run into issues connecting to your CARLA server, please verify the path to the CARLA python dependencies in the top of src/sim_nuscenes.py is correct. The code is already set up to render depth data (the depth is used to filter out occluded bounding boxes), but this depth data is not saved to disk currently. To add additional sensors (e.g. segmentation, etc), you can modify the render() function in src/sim_nuscenes.py. Let me know if you have any questions and I'll be happy to help!

**Comment by abhi1kumar** [comment]
@tzofi Thank you. It helps a lot.
